name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Java 17 (Requerido para compilar en Android actualmente)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 2. Python 3.10 (Muy estable)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Flutter (Usamos 'stable' para tener la última versión y evitar que Flet pida actualizar)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # 4. Instalar Flet
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flet

      # 5. Construir APK con el "Truco Linux" (Auto-aceptar preguntas)
      # El símbolo '|' (pipe) pasa la "y" al comando flet build
      - name: Build APK
        run: |
          yes | flet build apk --verbose

      # 6. Subir el archivo
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: habit-tracker-apk
          path: build/apk/app-release.apk
